databases:
  - name: sema
    databaseName: sema
    user: sema

services:
  - type: web
    name: sema
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sema
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false